---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: template_slug-ingress
  namespace: template_namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/force-ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.org/proxy-connect-timeout: "45s"
    nginx.org/proxy-read-timeout: "45s"
    nginx.org/client-max-body-size: "20m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - template_endpoint
    secretName: letsencrypt-prod
  rules:
  - host: template_endpoint
    http:
      paths:
      - path: /
        pathType: Prefix        
        backend:
          service:
            name: app
            port: 
              number: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: template_namespace
spec:
  type: ClusterIP
  selector:
    app: template_slug
  ports:
    - port: 5000
      name: http
