apiVersion: apps/v1
kind: Deployment
metadata:
  name: template_slug
  namespace: template_slug
  labels:
    app: template_slug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template_slug
  template:
    metadata:
      labels:
        app: template_slug
    spec:
      containers:
        - name: template_slug
          image: template_registry
          imagePullPolicy: Always
          resources: 
            requests: 
              memory: "50Mi"
              cpu: "10m"
            limits: 
              memory: "500Mi"
              cpu: "100m"
          terminationMessagePath: "/var/term.log"
          env:
            - name: APP
              value: "template_slug"
            - name: VERSION
              value: "1.0"
      imagePullSecrets:
      - name: devspace-pull-secrets