apiVersion: v1
clusters:
- cluster:
    server: template_cluster
    insecure-skip-tls-verify: true
  name: default
contexts:
- context:
    cluster: default
    namespace: template_namespace # namespace name
    user: template_user # user name
  name: template_user@default
current-context: template_user@default
kind: Config
preferences: {}
users:
- name: template_user
  user:
    client-certificate-data: template_certdata
    client-key-data: template_keydata