apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: kenzap-app-slug
spec:
  groups:
  - system:authenticated
  request: kenzap-app-slug-request
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth