apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kenzap-slug-role-binding
  namespace: kenzap-namespace
subjects:
- kind: User
  name: kenzap-slug
  namespace: kenzap-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kenzap-slug-roles