kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kenzap-namespace
  name: kenzap-slug-roles
rules:
- apiGroups: ["","networking.k8s.io", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "pods/exec", "services", "ingresses", "configmaps", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]